# Generated by Django 4.2.3 on 2023-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_staff_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
